### ISSUE TITLE
Alternatives to plugin config based on composer-config-plugin

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/yii-core#118]
I was reading about composer-config-plugin in Yii3, to give default extension config.
Why could not default config be put inside Module, using it through a ModuleInterface implementation?

Because using composer-config-plugin the extension default config will be read only using composer. Instead, having default config inside the module, it will be always read, when the module is loaded by Yii 

Also to avoid common problems, as written here:

https://yii3.idk.tn/site/config

> When developing with Yii 3, especially the first days, you may find yourself not getting the results expected only to later understand that you forgot to run composer du, and that your new configuration isn't taken into account.

I think that it is not intuitive that a problem with framework/web application should be solved checking composer tool.

**Comment by machour** [comment]
To install an extension, you will be using `composer install` which will automatically dump autoload when it's done. So the installed extension configuration is always read and applied.

As for your own configuration, and to be fair, I hadn't forgotten to `composer du` since I wrote that sentence.
You can make it happen automatically during dev (check the index.php in yii3-kitchen-sink), or even set up a gulp task to watch the config/ folder and run composer du every time you make a change here.

**Comment by FabrizioCaldarelli** [comment]
But would it be simpler to add a configuration inside the Module?

What are pro/cons/differences to put configuration directly inside the Module, instead using composer?

I like that all belongs to framework, it should be handled inside the framework and not delegated to other tools, as composer or gulp.

**Comment by machour** [comment]
what do you call "inside the module" ?

**Comment by FabrizioCaldarelli** [comment]
Take for example Behavior, main class of yii2-yandex-metrika:

https://github.com/hiqdev/yii2-yandex-metrika/blob/master/src/Behavior.php

that is the starter class called from framework (based on default config):

Keeping old configuration style, defining compnents inside main web.php config file in application:

```
return [
    'components' => [
        'view' => [
            'YandexMetrika' => [
                'class' => \hiqdev\yii2\YandexMetrika\Behavior::class,
            ],
        ],
    ],
];
```

Suppose now to have a framework known interface called ExtensionConfigInterface that has a "loadDefaultConfiguration" method.

Now, if \hiqdev\yii2\YandexMetrika\Behavior was extending this interface and implementing "loadDefaultConfiguration", it would pass to framework its default configuration values, such as now is done with composer-config-plugin.

But this should be done all inside the framework, without delegating to other external tools.

**Comment by hiqsol** [comment]
@FabrizioCaldarelli I've tried that way - I failed to make good of it.

All the configs merging has to be done before running framework. If this statement is not clear for you then you need to try it. For example, you can't merge any component config after it is instantiated, you have to merge it before. So you'll need to collect all the configs (so instantiate ALL the Config objects and call their `loadDefaultConfiguration` methods) then merge them and then run framework.

And then if you do it before running framework what is the difference is it a part of the framework or it is a standalone library. And the solution with the config plugin has several advantages:
- it has better performance because the config is not remerged at every request to an application
- configuration files location and contents are self-descriptive
- it is debuggable because one can see and debug assembled config
- it is NOT tightly coupled with application/framework, a developer is free to choose how to prepare their application config. Including your own way!

I've spent a lot of time trying the way you propose - https://github.com/hiqsol-attic/yii2-pluginmanager.
So I know what I'm talking about - it creates more problems then solves. If you don't believe me, please try to implement it! Maybe I'm wrong, but, please, show us something that looks like working and not a bare idea.

**Comment by FabrizioCaldarelli** [comment]
@hiqsol I believe you and in your tests but, what's wrong in writing plain config, instead using autoconfig?

Are there so much benefits in using default configurations, sometimes also hiding component presence (such as yandex metrika example) ?

Don't you think that in this way we could have a lot of components that do not appear in app configuration but do their work?

I tell you this because I don't like that the apps could hide their presence or depend from other tool. So, maybe, I'd like to split big configuration in multiple files, for example db.php, i18n.php, etc.. etc..., although my configuration files are never too much long.

**Comment by hiqsol** [comment]
Maybe I don't understand your idea completely...
What do you mean "writing plain config"? How will it be applied?
Could you please show me the code for I could evaluate it.

**Comment by FabrizioCaldarelli** [comment]
Sorry, I mean writing single files for single parts of configuration (db.php, i18n.php, etc..) and eventually single file for each components, even if I think this is not necessary.

Anyway, my doubts are about:

1. eventually hidden presence of components using configuration from composer;
2. really need to add default configuration to an extension or component, introducing a new development standard for new extension (for Yii3);

**Comment by hiqsol** [comment]
I think that there are no problems with configuration that just sits and does nothing when it is not used.

Also please take a look at Symfony Flex. It has very different implementation but similar goal: enable packages provide their configration.

**Comment by FabrizioCaldarelli** [comment]
OK, I'll take a look.

**Comment by FabrizioCaldarelli** [comment]
> Also please take a look at Symfony Flex. It has very different implementation but similar goal: enable packages provide their configration.

I'm looking into Symfony Flex and the first biggest difference between composer-config-plugin and Flex is that Flex put only the single component settings inside configuration and nothing else, differently from composer-config-plugin that merges configuration from all packages tree of dependencies.

This behaviour could be avoided in composer-config-plugin removing configuration in "not component packages", such as "yii-web", that configures more the just one single component. In that case it does too much work, more that it should.
