### ISSUE TITLE
Development checklist

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/yii-core#122]
How can new contributors help with development?

At the moment the community can contribute only with Issues and translations, but it is not clear what are areas or section where new contributors can help.

**Comment by machour** [comment]
I think that we should focus on getting all tests to work again. 
Pick any package with a red badge and give it a go: https://github.com/yiisoft/docs/blob/master/000-packages.md

I'm currently fixing all those grey badges, so that we only have red and green. 

Once tests are fixed, we will enforce testing again by requiring that all PRs passes them. 

(Already fixed gii, PR merge pending)

**Comment by FabrizioCaldarelli** [comment]
Thank you, this is exactly what I was looking for.
