### ISSUE TITLE
SOLID compliance

### ISSUE THREAD

**Issue by omsi668** [yiisoft/yii-core#185]
Hello,

This is not a proper bug. More a discussion i can't start on the Yii Forum.

In the roadmap it is announced that Yii3 will follow best practive as SOLID : 

"Be based on best practices such as SOLID, GRASP etc. and teach them to community."

But, i'm following the dev of Yii3, and what I see is that there is a lot of attributes in new classes déclared as private, which, for me, completely breaks the Open Close Principle of SOLID.

"In object-oriented programming, the open/closed principle states "software entities (classes, modules, functions, etc.) should be open for extension, but closed for modification";[1] that is, such an entity can allow its behaviour to be extended without modifying its source code. " (Wikipedia).

I think most of these must be declared protected to ensure SOLID compatibility. Is it planned?

Thank you

| Q                | A
| ---------------- | ---
| Yii version      | 3.*
| PHP version      | 
| Operating system |

**Comment by rob006** [comment]
I think you're misinterpreting open/closed principle. It is not about "make everything public/protected, so I can change everything". It is about allowing to change one implementation by another, so you can use custom components without changing framework code. For example, you can freely change DB or URL manager components without editing a single Yii file. It already works pretty fine in Yii 2, and in Yii 3 should be even easier due to relying on DI and interfaces.

**Comment by samdark** [comment]
Why can't you start it at the forum?

**Comment by omsi668** [comment]
@samdark Ok i'll post there, i thought i couldn't create a new topic but i can in the "questions" subforum, my bad
